/////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////
//            Demon Tower, Level 1 (MOBHA5.ARE)
/////////////////////////////////////////////////////////////////////
//        Version 1
// The player confronts a Merilith and will face Succubuses, 
// Erinyes, and Demon Knights.
//
/////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
// Set Rest Encounter Probability (tied to difficulty slider)
/////////////////////////////////////////////////////////////////////
IF 
	DifficultyGT(HARD)
	!Global("MO_RestEncounter","MOBHA5",1)
THEN
	RESPONSE #100
		SetRestEncounterProbabilityDay(75) 
		SetRestEncounterProbabilityNight(75)
		SetGlobal("MO_RestEncounter","MOBHA5",1) 
END

IF 
	Difficulty(HARD)
	!Global("MO_RestEncounter","MOBHA5",2)
THEN
	RESPONSE #100
		SetRestEncounterProbabilityDay(50) 
		SetRestEncounterProbabilityNight(50)
		SetGlobal("MO_RestEncounter","MOBHA5",2) 
END

IF 
	Difficulty(NORMAL)
	!Global("MO_RestEncounter","MOBHA5",3)
THEN
	RESPONSE #100
		SetRestEncounterProbabilityDay(25) 
		SetRestEncounterProbabilityNight(25)
		SetGlobal("MO_RestEncounter","MOBHA5",3) 
END

IF 
	DifficultyLT(NORMAL)
	!Global("MO_RestEncounter","MOBHA5",4)
THEN
	RESPONSE #100
		SetRestEncounterProbabilityDay(10) 
		SetRestEncounterProbabilityNight(10)
		SetGlobal("MO_RestEncounter","MOBHA5",4) 
END