/////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////
//            Demon Tower, Level 1 (MOBHA5.ARE)
/////////////////////////////////////////////////////////////////////
//        Version 1
// The player confronts a Merilith and will face Succubuses, 
// Erinyes, and Demon Knights.
//
/////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
// Set Rest Encounter Probability (tied to difficulty slider)
/////////////////////////////////////////////////////////////////////
IF 
	DifficultyGT(HARD)
	!Global("MO_RestEncounter","MOBHA5",1)
THEN
	RESPONSE #100
		SetRestEncounterProbabilityDay(75) 
		SetRestEncounterProbabilityNight(75)
		SetGlobal("MO_RestEncounter","MOBHA5",1) 
END

IF 
	Difficulty(HARD)
	!Global("MO_RestEncounter","MOBHA5",2)
THEN
	RESPONSE #100
		SetRestEncounterProbabilityDay(50) 
		SetRestEncounterProbabilityNight(50)
		SetGlobal("MO_RestEncounter","MOBHA5",2) 
END

IF 
	Difficulty(NORMAL)
	!Global("MO_RestEncounter","MOBHA5",3)
THEN
	RESPONSE #100
		SetRestEncounterProbabilityDay(25) 
		SetRestEncounterProbabilityNight(25)
		SetGlobal("MO_RestEncounter","MOBHA5",3) 
END

IF 
	DifficultyLT(NORMAL)
	!Global("MO_RestEncounter","MOBHA5",4)
THEN
	RESPONSE #100
		SetRestEncounterProbabilityDay(10) 
		SetRestEncounterProbabilityNight(10)
		SetGlobal("MO_RestEncounter","MOBHA5",4) 
END

/////////////////////////////////////////////////////////////////////
// Block Exit
/////////////////////////////////////////////////////////////////////
IF
    Global("Enteredmobha5","GLOBAL",0)
THEN
    RESPONSE #100
        SetGlobal("Enteredmobha5","GLOBAL",1)
        TriggerActivation("TrMOBHA1",FALSE)
        TriggerActivation("TrMOBHA6",FALSE)
END

IF
  Dead("mobha20")
  CombatCounter(0)
  Global("DoorOpenmobha5","mobha5",0)
THEN 
    RESPONSE #100
      TriggerActivation("TrMOBHA1",TRUE)
        TriggerActivation("TrMOBHA6",TRUE)
      SetGlobal("DoorOpenmobha5","mobha5",1)
END