IF
	IsOverMe([GOODCUTOFF])
	Global("MO_Spawn03","MOBHA1",0)
THEN
	RESPONSE #100
		SetGlobal("MO_Spawn03","MOBHA1",1)
		CreateCreature("mobha06",[2824.520],S)  // Skirmisher
		CreateCreature("mobha06",[2896.526],S)  // Skirmisher
		CreateCreature("mobha06",[2857.417],S)  // Skirmisher
		CreateCreature("mobha05",[2770.288],S)  // Scout
		CreateCreature("mobha05",[2850.626],S)  // Scout
		CreateCreature("mobha05",[2966.223],S)  // Scout
END