/////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////
//            Zendrilar
/////////////////////////////////////////////////////////////////////
//        Version 1
// Archlich, 31-22 Cleric/Mage
//
// 
/////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
// Truesight Timer
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_EnemyTrueSightTimer","GLOBAL")
  Global("MO_EnemyTrueSight","GLOBAL",1)
THEN
  RESPONSE #100
    SetGlobal("MO_EnemyTrueSight","GLOBAL",0)
END

IF
  Global("MO_TrueSightActive","LOCALS",1)
  CheckStat(Myself,0,TRUE_SIGHT)
THEN
  RESPONSE #100
    SetGlobal("MO_TrueSightActive","LOCALS",0)
    SetGlobal("MO_EnemyTrueSight","GLOBAL",0)
END

/////////////////////////////////////////////////////////////////////
// Prep
/////////////////////////////////////////////////////////////////////
IF
  Global("Prep","LOCALS",0)
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    ApplySpell(Myself,WIZARD_STONE_SKIN)  // SPWI408.SPL (Stoneskin)
    ApplySpell(Myself,WIZARD_SPELL_SHIELD)  // SPWI519.SPL (Spell Shield)
    ApplySpell(Myself,CLERIC_SHIELD_OF_THE_ARCHONS)  // SPPR701.SPL (Shield of the Archons)
    ApplySpell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)  // SPWI611.SPL (Protection From Magical Weapons)
    ApplySpell(Myself,WIZARD_PROTECTION_FROM_THE_ELEMENTS)  // SPWI702.SPL (Protection From The Elements))
    ApplySpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
    ApplySpell(Myself,WIZARD_SPELL_IMMUNITY_DIVINATION)  // SPWI592.SPL (Immunity: Divination)
    ApplySpell(Myself,WIZARD_MIRROR_IMAGE)
    ApplySpell(Myself,WIZARD_FIRE_SHIELD_RED)
    ApplySpell(Myself,CLERIC_GLOBE_OF_BLADES)
    SetGlobal("MO_ImprovedAlacrity","LOCALS",1)
    SetGlobal("MO_TimeStop","LOCALS",1)
    SetGlobal("Prep","LOCALS",1)
END

/////////////////////////////////////////////////////////////////////
// Contingency
/////////////////////////////////////////////////////////////////////
IF
  Global("Contingency","LOCALS",0)
  TookDamage()
THEN
  RESPONSE #100
    ApplySpell(Myself,WIZARD_SPELL_IMMUNITY_DIVINATION)  // SPWI592.SPL (Immunity: Divination)
    ApplySpell(Myself,WIZARD_MISLEAD)  // SPWI607.SPL (Mislead)
    ApplySpell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
    SetGlobal("Contingency","LOCALS",1)
END

/////////////////////////////////////////////////////////////////////
// Spell Trigger
/////////////////////////////////////////////////////////////////////
IF
  See(FarthestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStatGT(LastSeenBy(Myself),35,RESISTMAGIC)
  Global("SpellTrigger","LOCALS",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    DisplayString(Myself,39968)  // ~Spell Trigger - Fired~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_ICE_STORM)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY) 
    SetGlobal("SpellTrigger","LOCALS",1)
    SetInterrupt(TRUE)
  RESPONSE #100
    SetInterrupt(FALSE)
    DisplayString(Myself,39968)  // ~Spell Trigger - Fired~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_SKULL_TRAP)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY) 
    SetGlobal("SpellTrigger","LOCALS",1)
    SetInterrupt(TRUE)
  RESPONSE #100
    SetInterrupt(FALSE)
    DisplayString(Myself,39968)  // ~Spell Trigger - Fired~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_DEATH_FOG)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY) 
    SetGlobal("SpellTrigger","LOCALS",1)
    SetInterrupt(TRUE)
END

IF
  See(SecondFarthestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStatGT(LastSeenBy(Myself),35,RESISTMAGIC)
  Global("SpellTrigger","LOCALS",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    DisplayString(Myself,39968)  // ~Spell Trigger - Fired~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_ICE_STORM)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY) 
    SetGlobal("SpellTrigger","LOCALS",1)
    SetInterrupt(TRUE)
  RESPONSE #100
    SetInterrupt(FALSE)
    DisplayString(Myself,39968)  // ~Spell Trigger - Fired~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_SKULL_TRAP)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY) 
    SetGlobal("SpellTrigger","LOCALS",1)
    SetInterrupt(TRUE)
  RESPONSE #100
    SetInterrupt(FALSE)
    DisplayString(Myself,39968)  // ~Spell Trigger - Fired~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_DEATH_FOG)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY) 
    SetGlobal("SpellTrigger","LOCALS",1)
    SetInterrupt(TRUE)
END

IF
  See(ThirdFarthestEnemyOf(Myself))
  !HasBounceEffects(LastSeenBy(Myself))
  !CheckStatGT(LastSeenBy(Myself),35,RESISTMAGIC)
  Global("SpellTrigger","LOCALS",0)
THEN
  RESPONSE #100
    SetInterrupt(FALSE)
    DisplayString(Myself,39968)  // ~Spell Trigger - Fired~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_ICE_STORM)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY) 
    SetGlobal("SpellTrigger","LOCALS",1)
    SetInterrupt(TRUE)
  RESPONSE #100
    SetInterrupt(FALSE)
    DisplayString(Myself,39968)  // ~Spell Trigger - Fired~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_SKULL_TRAP)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY) 
    SetGlobal("SpellTrigger","LOCALS",1)
    SetInterrupt(TRUE)
  RESPONSE #100
    SetInterrupt(FALSE)
    DisplayString(Myself,39968)  // ~Spell Trigger - Fired~
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_DEATH_FOG)
    ReallyForceSpell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_INVISIBILITY) 
    SetGlobal("SpellTrigger","LOCALS",1)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Defensive
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(NearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
  !CheckSpellState(Myself,PROTECTION_FROM_MAGICAL_WEAPONS)
  !CheckSpellState(Myself,ABSOLUTE_IMMUNITY)
  !CheckSpellState(Myself,MANTLE)
  !CheckSpellState(Myself,IMPROVED_MANTLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_PROTECTION_FROM_MAGIC_WEAPONS)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See([GOODCUTOFF])
  HaveSpell(WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
  StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_VOCALIZE)  // SPWI219.SPL (Vocalize)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Spell Immunity
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See([GOODCUTOFF])
  HaveSpell(WIZARD_SPELL_IMMUNITY)  // SPWI510.SPL (Spell Immunity)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastSpellImmunity","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastSpellImmunity","LOCALS",0)
    Continue()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastSpellImmunity","LOCALS",1)
  HaveSpell(WIZARD_SPELL_IMMUNITY)  // SPWI510.SPL (Spell Immunity)
  See([GOODCUTOFF])
  !CheckSpellState(Myself,SI_ABJURATION)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  RandomNum(2,1)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastSpellImmunity","LOCALS",1)
  HaveSpell(WIZARD_SPELL_IMMUNITY)  // SPWI510.SPL (Spell Immunity)
  See([GOODCUTOFF])
  !CheckSpellState(Myself,SI_DIVINATION)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
  RandomNum(2,2)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_SPELL_IMMUNITY_DIVINATION)  // SPWI592.SPL (Immunity: Divination)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastSpellImmunity","LOCALS",1)
  HaveSpell(WIZARD_SPELL_IMMUNITY)  // SPWI510.SPL (Spell Immunity)
  See([GOODCUTOFF])
  !CheckSpellState(Myself,SI_DIVINATION)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_SPELL_IMMUNITY_DIVINATION)  // SPWI592.SPL (Immunity: Divination)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastSpellImmunity","LOCALS",1)
  HaveSpell(WIZARD_SPELL_IMMUNITY)  // SPWI510.SPL (Spell Immunity)
  See([GOODCUTOFF])
  !CheckSpellState(Myself,SI_ABJURATION)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_SPELL_IMMUNITY_ABJURATION)  // SPWI590.SPL (Immunity: Abjuration)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Protection from the Elements
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(NearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_PROTECTION_FROM_THE_ELEMENTS)  // SPWI702.SPL (Protection From The Elements)
  !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_ENERGY)
  !CheckStatGT(Myself,0,WIZARD_PROTECTION_FROM_THE_ELEMENTS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_PROTECTION_FROM_THE_ELEMENTS)  // SPWI702.SPL (Protection From The Elements)
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Heal/Cure
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HPPercentLT(Myself,50)
  HaveSpell(CLERIC_HEAL)  // SPPR607.SPL (Heal)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,CLERIC_HEAL)  // SPPR607.SPL (Heal)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(CLERIC_MASS_CURE)  // SPPR514.SPL (Mass Cure)
  HPPercentLT(SecondNearest([EVILCUTOFF]),80)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("MO_WondrousRecallCounter","LOCALS",1)
    SetInterrupt(FALSE)
    Spell(SecondNearest([EVILCUTOFF]),CLERIC_MASS_CURE)  // SPPR514.SPL (Mass Cure)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(CLERIC_MASS_CURE)  // SPPR514.SPL (Mass Cure)
  HPPercentLT(ThirdNearest([EVILCUTOFF]),80)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("MO_WondrousRecallCounter","LOCALS",1)
    SetInterrupt(FALSE)
    Spell(ThirdNearest([EVILCUTOFF]),CLERIC_MASS_CURE)  // SPPR514.SPL (Mass Cure)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(CLERIC_MASS_CURE)  // SPPR514.SPL (Mass Cure)
  HPPercentLT(FourthNearest([EVILCUTOFF]),80)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("MO_WondrousRecallCounter","LOCALS",1)
    SetInterrupt(FALSE)
    Spell(FourthNearest([EVILCUTOFF]),CLERIC_MASS_CURE)  // SPPR514.SPL (Mass Cure)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(CLERIC_MASS_CURE)  // SPPR514.SPL (Mass Cure)
  HPPercentLT(FifthNearest([EVILCUTOFF]),80)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("MO_WondrousRecallCounter","LOCALS",1)
    SetInterrupt(FALSE)
    Spell(FifthNearest([EVILCUTOFF]),CLERIC_MASS_CURE)  // SPPR514.SPL (Mass Cure)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(CLERIC_MASS_CURE)  // SPPR514.SPL (Mass Cure)
  HPPercentLT(SixthNearest([EVILCUTOFF]),60)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("MO_WondrousRecallCounter","LOCALS",1)
    SetInterrupt(FALSE)
    Spell(SixthNearest([EVILCUTOFF]),CLERIC_MASS_CURE)  // SPPR514.SPL (Mass Cure)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(CLERIC_MASS_CURE)  // SPPR514.SPL (Mass Cure)
  HPPercentLT(SeventhNearest([EVILCUTOFF]),60)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("MO_WondrousRecallCounter","LOCALS",1)
    SetInterrupt(FALSE)
    Spell(SeventhNearest([EVILCUTOFF]),CLERIC_MASS_CURE)  // SPPR514.SPL (Mass Cure)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(CLERIC_MASS_CURE)  // SPPR514.SPL (Mass Cure)
  HPPercentLT(EighthNearest([EVILCUTOFF]),80)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("MO_WondrousRecallCounter","LOCALS",1)
    SetInterrupt(FALSE)
    Spell(ThirdNearest([EVILCUTOFF]),CLERIC_MASS_CURE)  // SPPR514.SPL (Mass Cure)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(CLERIC_MASS_CURE)  // SPPR514.SPL (Mass Cure)
  HPPercentLT(NinthNearest([EVILCUTOFF]),80)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("MO_WondrousRecallCounter","LOCALS",1)
    SetInterrupt(FALSE)
    Spell(NinthNearest([EVILCUTOFF]),CLERIC_MASS_CURE)  // SPPR514.SPL (Mass Cure)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(CLERIC_MASS_CURE)  // SPPR514.SPL (Mass Cure)
  HPPercentLT(TenthNearest([EVILCUTOFF]),80)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("MO_WondrousRecallCounter","LOCALS",1)
    SetInterrupt(FALSE)
    Spell(TenthNearest([EVILCUTOFF]),CLERIC_MASS_CURE)  // SPPR514.SPL (Mass Cure)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Zone of Sweet Air
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  HaveSpell(CLERIC_ZONE_OF_SWEET_AIR)  // SPPR318.SPL (Zone of Sweet Air)
  OR(12)
    SpellCast([GOODCUTOFF.0.0.MAGE_ALL],WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
    SpellCast([GOODCUTOFF.0.0.MAGE_ALL],WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
    SpellCast([GOODCUTOFF.0.0.MAGE_ALL],WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
    SpellCast([GOODCUTOFF.0.0.MAGE_ALL],WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
    SpellCast([GOODCUTOFF.0.0.BARD_ALL],WIZARD_INCENDIARY_CLOUD)  // SPWI810.SPL (Incendiary Cloud)
    SpellCast([GOODCUTOFF.0.0.BARD_ALL],WIZARD_STINKING_CLOUD)  // SPWI213.SPL (Stinking Cloud)
    SpellCast([GOODCUTOFF.0.0.BARD_ALL],WIZARD_CLOUDKILL)  // SPWI502.SPL (Cloudkill)
    SpellCast([GOODCUTOFF.0.0.BARD_ALL],WIZARD_DEATH_FOG)  // SPWI614.SPL (Death Fog)
    SpellCast([GOODCUTOFF.0.0.SHAMAN],CLERIC_WRITHING_FOG)  // SPPR250.SPL (Writhing Fog)
    SpellCast([GOODCUTOFF],TRAP_STINKING_CLOUD)  // SPWI004.SPL (Stinking Cloud)
    SpellCast([GOODCUTOFF],SPORE_DEATH)  // SPIN673.SPL (Cloudkill)
    SpellCast([GOODCUTOFF],TRAP_CLOUDKILL)  // SPWI016.SPL (Cloudkill)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !StateCheck(Myself,STATE_SILENCED)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    IncrementGlobal("MO_WondrousRecallCounter","LOCALS",1)
    SetInterrupt(FALSE)
    Spell(Myself,CLERIC_ZONE_OF_SWEET_AIR)  // SPPR318.SPL (Zone of Sweet Air)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Timestop
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  GlobalGT("MO_TimeStop","LOCALS",0)
  See(NearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_TimeStop","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_TimeStopTimer","LOCALS",30)
    SetInterrupt(FALSE)
    ForceSpell(Myself,WIZARD_TIME_STOP)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Improved Alactrity - Used ONLY after Time Stop
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalTimerNotExpired("MO_TimeStopTimer","LOCALS")
  GlobalGT("MO_ImprovedAlacrity","LOCALS",0)
  OR(2)
    See(NearestEnemyOfType([GOODCUTOFF]))
    ActuallyInCombat()
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    IncrementGlobal("MO_ImprovedAlacrity","LOCALS",-1)
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    SpellNoDec(Myself,WIZARD_IMPROVED_ALUCRITY)  // SPWI921.SPL (Improved Alacrity)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Remove Magic
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  See(NearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  HaveSpell(WIZARD_REMOVE_MAGIC)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RemoveMagicTimer","LOCALS",18)
    IncrementGlobal("Remove","LOCALS",-1)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  HaveSpell(WIZARD_REMOVE_MAGIC)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RemoveMagicTimer","LOCALS",18)
    IncrementGlobal("Remove","LOCALS",-1)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  HaveSpell(WIZARD_REMOVE_MAGIC)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RemoveMagicTimer","LOCALS",18)
    IncrementGlobal("Remove","LOCALS",-1)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  HaveSpell(WIZARD_REMOVE_MAGIC)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RemoveMagicTimer","LOCALS",18)
    IncrementGlobal("Remove","LOCALS",-1)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  HaveSpell(WIZARD_REMOVE_MAGIC)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RemoveMagicTimer","LOCALS",18)
    IncrementGlobal("Remove","LOCALS",-1)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RemoveMagicTimer","LOCALS")
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  HaveSpell(WIZARD_REMOVE_MAGIC)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RemoveMagicTimer","LOCALS",18)
    IncrementGlobal("Remove","LOCALS",-1)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_REMOVE_MAGIC)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Breach
/////////////////////////////////////////////////////////////////////
IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !Global("MO_DamagedTarget","LOCALS",1)
  !GlobalTimerNotExpired("MO_BreachTimer","LOCALS")
  See(NearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_BreachTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !Global("MO_DamagedTarget","LOCALS",1)
  !GlobalTimerNotExpired("MO_BreachTimer","LOCALS")
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_BreachTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !Global("MO_DamagedTarget","LOCALS",1)
  !GlobalTimerNotExpired("MO_BreachTimer","LOCALS")
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_BreachTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !Global("MO_DamagedTarget","LOCALS",1)
  !GlobalTimerNotExpired("MO_BreachTimer","LOCALS")
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_BreachTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !Global("MO_DamagedTarget","LOCALS",1)
  !GlobalTimerNotExpired("MO_BreachTimer","LOCALS")
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_BreachTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

IF
  !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
  !Global("MO_DamagedTarget","LOCALS",1)
  !GlobalTimerNotExpired("MO_BreachTimer","LOCALS")
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_BREACH)  // SPWI513.SPL (Breach)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  !CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_BreachTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BREACH)  // SPWI513.SPL (Breach)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Ruby Ray of Reversal
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RubyRayTimer","LOCALS")
  See(NearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(7)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RubyRayTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RubyRayTimer","LOCALS")
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(7)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RubyRayTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RubyRayTimer","LOCALS")
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(7)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RubyRayTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RubyRayTimer","LOCALS")
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(7)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RubyRayTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RubyRayTimer","LOCALS")
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(7)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RubyRayTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_RubyRayTimer","LOCALS")
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
  OR(4)
    CheckSpellState(LastSeenBy(Myself),PROTECTION_FROM_MAGICAL_WEAPONS)
    CheckSpellState(LastSeenBy(Myself),ABSOLUTE_IMMUNITY)
    CheckSpellState(LastSeenBy(Myself),IMPROVED_MANTLE)
    CheckSpellState(LastSeenBy(Myself),MANTLE)
  OR(7)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
    CheckSpellState(LastSeenBy(Myself),SPELL_SHIELD)
    CheckSpellState(LastSeenBy(Myself),SI_ABJURATION)
    CheckSpellState(LastSeenBy(Myself),SI_DIVINATION)
    CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
    CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckSpellState(LastSeenBy(Myself),SCROLL_OF_PROTECTION_FROM_MAGIC)
  CheckStatLT(LastSeenBy(Myself),1,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_RubyRayTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_RUBY_RAY_OF_REVERSAL)  // SPWI704.SPL (Ruby Ray of Reversal)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Bigby's Crushing Hand
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See([GOODCUTOFF])
  HaveSpell(WIZARD_BIGBYS_CRUSHING_HAND)  // SPWI918.SPL (Bigby's Crushing Hand)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastBigbys","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastBigbys","LOCALS",0)
    Continue()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastBigbys","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),5)
  HaveSpell(WIZARD_BIGBYS_CRUSHING_HAND)  // SPWI918.SPL (Bigby's Crushing Hand)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),99,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CRUSHING_HAND)  // SPWI918.SPL (Bigby's Crushing Hand)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastBigbys","LOCALS",1)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),5)
  HaveSpell(WIZARD_BIGBYS_CRUSHING_HAND)  // SPWI918.SPL (Bigby's Crushing Hand)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),99,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CRUSHING_HAND)  // SPWI918.SPL (Bigby's Crushing Hand)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastBigbys","LOCALS",1)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),5)
  HaveSpell(WIZARD_BIGBYS_CRUSHING_HAND)  // SPWI918.SPL (Bigby's Crushing Hand)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),99,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CRUSHING_HAND)  // SPWI918.SPL (Bigby's Crushing Hand)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastBigbys","LOCALS",1)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),5)
  HaveSpell(WIZARD_BIGBYS_CRUSHING_HAND)  // SPWI918.SPL (Bigby's Crushing Hand)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),99,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CRUSHING_HAND)  // SPWI918.SPL (Bigby's Crushing Hand)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastBigbys","LOCALS",1)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),5)
  HaveSpell(WIZARD_BIGBYS_CRUSHING_HAND)  // SPWI918.SPL (Bigby's Crushing Hand)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),99,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CRUSHING_HAND)  // SPWI918.SPL (Bigby's Crushing Hand)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastBigbys","LOCALS",1)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Range(LastSeenBy(Myself),5)
  HaveSpell(WIZARD_BIGBYS_CRUSHING_HAND)  // SPWI918.SPL (Bigby's Crushing Hand)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_FEEBLEMINDED)
  !CheckStatGT(LastSeenBy(Myself),0,HELD)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckSpellState(LastSeenBy(Myself),SI_EVOCATION)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),99,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_BIGBYS_CRUSHING_HAND)  // SPWI918.SPL (Bigby's Crushing Hand)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Energy Drain
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See([GOODCUTOFF])
  HaveSpell(WIZARD_ENERGY_DRAIN)  // SPWI914.SPL (Energy Drain)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastEnergyDrain","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastEnergyDrain","LOCALS",0)
    Continue()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastEnergyDrain","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_ENERGY_DRAIN)  // SPWI914.SPL (Energy Drain)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !CheckSpellState(LastSeenBy(Myself),LATHANDER_BOON)
  CheckStat(LastSeenBy(Myself),0,LEVEL_DRAIN_IMMUNITY)
  !CheckStatGT(LastSeenBy(Myself),35,RESISTMAGIC)
  !HasItemEquiped("AMUL21",Myself)  // Amulet of Power
  !HasItemEquipedReal("BLUN25",LastSeenBy(Myself))  // Mace of Disruption +2
  !HasItemEquipedReal("HAMM10",LastSeenBy(Myself))  // Runehammer +4
  !HasItemEquipedReal("HAMM11",LastSeenBy(Myself))  // Runehammer +5
  !HasItemEquipedReal("SW1H69",LastSeenBy(Myself))  // Spectral Brand +5
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_ENERGY_DRAIN)  // SPWI914.SPL (Energy Drain)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastEnergyDrain","LOCALS",1)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_ENERGY_DRAIN)  // SPWI914.SPL (Energy Drain)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !CheckSpellState(LastSeenBy(Myself),LATHANDER_BOON)
  CheckStat(LastSeenBy(Myself),0,LEVEL_DRAIN_IMMUNITY)
  !CheckStatGT(LastSeenBy(Myself),35,RESISTMAGIC)
  !HasItemEquiped("AMUL21",Myself)  // Amulet of Power
  !HasItemEquipedReal("BLUN25",LastSeenBy(Myself))  // Mace of Disruption +2
  !HasItemEquipedReal("HAMM10",LastSeenBy(Myself))  // Runehammer +4
  !HasItemEquipedReal("HAMM11",LastSeenBy(Myself))  // Runehammer +5
  !HasItemEquipedReal("SW1H69",LastSeenBy(Myself))  // Spectral Brand +5
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_ENERGY_DRAIN)  // SPWI914.SPL (Energy Drain)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastEnergyDrain","LOCALS",1)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_ENERGY_DRAIN)  // SPWI914.SPL (Energy Drain)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !CheckSpellState(LastSeenBy(Myself),LATHANDER_BOON)
  CheckStat(LastSeenBy(Myself),0,LEVEL_DRAIN_IMMUNITY)
  !CheckStatGT(LastSeenBy(Myself),35,RESISTMAGIC)
  !HasItemEquiped("AMUL21",Myself)  // Amulet of Power
  !HasItemEquipedReal("BLUN25",LastSeenBy(Myself))  // Mace of Disruption +2
  !HasItemEquipedReal("HAMM10",LastSeenBy(Myself))  // Runehammer +4
  !HasItemEquipedReal("HAMM11",LastSeenBy(Myself))  // Runehammer +5
  !HasItemEquipedReal("SW1H69",LastSeenBy(Myself))  // Spectral Brand +5
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_ENERGY_DRAIN)  // SPWI914.SPL (Energy Drain)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastEnergyDrain","LOCALS",1)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_ENERGY_DRAIN)  // SPWI914.SPL (Energy Drain)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !CheckSpellState(LastSeenBy(Myself),LATHANDER_BOON)
  CheckStat(LastSeenBy(Myself),0,LEVEL_DRAIN_IMMUNITY)
  !CheckStatGT(LastSeenBy(Myself),35,RESISTMAGIC)
  !HasItemEquiped("AMUL21",Myself)  // Amulet of Power
  !HasItemEquipedReal("BLUN25",LastSeenBy(Myself))  // Mace of Disruption +2
  !HasItemEquipedReal("HAMM10",LastSeenBy(Myself))  // Runehammer +4
  !HasItemEquipedReal("HAMM11",LastSeenBy(Myself))  // Runehammer +5
  !HasItemEquipedReal("SW1H69",LastSeenBy(Myself))  // Spectral Brand +5
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_ENERGY_DRAIN)  // SPWI914.SPL (Energy Drain)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastEnergyDrain","LOCALS",1)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_ENERGY_DRAIN)  // SPWI914.SPL (Energy Drain)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !CheckSpellState(LastSeenBy(Myself),LATHANDER_BOON)
  CheckStat(LastSeenBy(Myself),0,LEVEL_DRAIN_IMMUNITY)
  !CheckStatGT(LastSeenBy(Myself),35,RESISTMAGIC)
  !HasItemEquiped("AMUL21",Myself)  // Amulet of Power
  !HasItemEquipedReal("BLUN25",LastSeenBy(Myself))  // Mace of Disruption +2
  !HasItemEquipedReal("HAMM10",LastSeenBy(Myself))  // Runehammer +4
  !HasItemEquipedReal("HAMM11",LastSeenBy(Myself))  // Runehammer +5
  !HasItemEquipedReal("SW1H69",LastSeenBy(Myself))  // Spectral Brand +5
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_ENERGY_DRAIN)  // SPWI914.SPL (Energy Drain)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastEnergyDrain","LOCALS",1)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_ENERGY_DRAIN)  // SPWI914.SPL (Energy Drain)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !Kit(LastSeenBy(Myself),UNDEADHUNTER)
  !CheckSpellState(LastSeenBy(Myself),LATHANDER_BOON)
  CheckStat(LastSeenBy(Myself),0,LEVEL_DRAIN_IMMUNITY)
  !CheckStatGT(LastSeenBy(Myself),35,RESISTMAGIC)
  !HasItemEquiped("AMUL21",Myself)  // Amulet of Power
  !HasItemEquipedReal("BLUN25",LastSeenBy(Myself))  // Mace of Disruption +2
  !HasItemEquipedReal("HAMM10",LastSeenBy(Myself))  // Runehammer +4
  !HasItemEquipedReal("HAMM11",LastSeenBy(Myself))  // Runehammer +5
  !HasItemEquipedReal("SW1H69",LastSeenBy(Myself))  // Spectral Brand +5
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_ENERGY_DRAIN)  // SPWI914.SPL (Energy Drain)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Greater Malison
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MalisonTimer","LOCALS")
  See([GOODCUTOFF])
  HaveSpell(WIZARD_GREATER_MALISON)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #80
    SetGlobal("MO_CastMalison","LOCALS",1)
    Continue()
  RESPONSE #20
    SetGlobal("MO_CastMalison","LOCALS",0)
    Continue()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MalisonTimer","LOCALS")
  Global("MO_CastMalison","LOCALS",1)
  HaveSpell(WIZARD_GREATER_MALISON)
  See(NearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !CheckSpellState(LastSeenBy(Myself),MALISON)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MalisonTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MalisonTimer","LOCALS")
  Global("MO_CastMalison","LOCALS",1)
  HaveSpell(WIZARD_GREATER_MALISON)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !CheckSpellState(LastSeenBy(Myself),MALISON)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MalisonTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MalisonTimer","LOCALS")
  Global("MO_CastMalison","LOCALS",1)
  HaveSpell(WIZARD_GREATER_MALISON)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !CheckSpellState(LastSeenBy(Myself),MALISON)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MalisonTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MalisonTimer","LOCALS")
  Global("MO_CastMalison","LOCALS",1)
  HaveSpell(WIZARD_GREATER_MALISON)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !CheckSpellState(LastSeenBy(Myself),MALISON)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MalisonTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MalisonTimer","LOCALS")
  Global("MO_CastMalison","LOCALS",1)
  HaveSpell(WIZARD_GREATER_MALISON)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !CheckSpellState(LastSeenBy(Myself),MALISON)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MalisonTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MalisonTimer","LOCALS")
  Global("MO_CastMalison","LOCALS",1)
  HaveSpell(WIZARD_GREATER_MALISON)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  !CheckSpellState(LastSeenBy(Myself),MALISON)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_ENCHANTMENT)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MalisonTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_GREATER_MALISON)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Teleport Field
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_TeleportTimer","LOCALS")
  See(NearestEnemyOfType([GOODCUTOFF]))
  Allegiance(Myself,ENEMY)
  HaveSpell(WIZARD_TELEPORT_FIELD)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_TeleportTimer","LOCALS",60)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_TELEPORT_FIELD)
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Maze
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  See([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
  HaveSpell(WIZARD_MAZE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastMaze","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastMaze","LOCALS",0)
    Continue()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  Global("MO_CastMaze","LOCALS",1)
  See(NearestEnemyOf(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Allegiance(Myself,ENEMY)
  Range(LastSeenBy(Myself),4)
  HaveSpell(WIZARD_MAZE)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),18,INT)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !Kit(LastSeenBy(Myself),BERSERKER)
  !Kit(LastSeenBy(Myself),BARBARIAN)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MazeTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MAZE)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  Global("MO_CastMaze","LOCALS",1)
  See(SecondNearestEnemyOf(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Allegiance(Myself,ENEMY)
  Range(LastSeenBy(Myself),4)
  HaveSpell(WIZARD_MAZE)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),18,INT)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !Kit(LastSeenBy(Myself),BERSERKER)
  !Kit(LastSeenBy(Myself),BARBARIAN)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MazeTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MAZE)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  Global("MO_CastMaze","LOCALS",1)
  See(ThirdNearestEnemyOf(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Allegiance(Myself,ENEMY)
  Range(LastSeenBy(Myself),4)
  HaveSpell(WIZARD_MAZE)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),18,INT)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !Kit(LastSeenBy(Myself),BERSERKER)
  !Kit(LastSeenBy(Myself),BARBARIAN)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MazeTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MAZE)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  Global("MO_CastMaze","LOCALS",1)
  See(FourthNearestEnemyOf(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Allegiance(Myself,ENEMY)
  Range(LastSeenBy(Myself),4)
  HaveSpell(WIZARD_MAZE)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),18,INT)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !Kit(LastSeenBy(Myself),BERSERKER)
  !Kit(LastSeenBy(Myself),BARBARIAN)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MazeTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MAZE)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  Global("MO_CastMaze","LOCALS",1)
  See(FifthNearestEnemyOf(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Allegiance(Myself,ENEMY)
  Range(LastSeenBy(Myself),4)
  HaveSpell(WIZARD_MAZE)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),18,INT)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !Kit(LastSeenBy(Myself),BERSERKER)
  !Kit(LastSeenBy(Myself),BARBARIAN)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MazeTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MAZE)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  !GlobalTimerNotExpired("MO_MazeTimer","LOCALS")
  Global("MO_CastMaze","LOCALS",1)
  See(SixthNearestEnemyOf(Myself))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  Allegiance(Myself,ENEMY)
  Range(LastSeenBy(Myself),4)
  HaveSpell(WIZARD_MAZE)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),18,INT)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !Kit(LastSeenBy(Myself),BERSERKER)
  !Kit(LastSeenBy(Myself),BARBARIAN)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetGlobalTimer("MO_MazeTimer","LOCALS",18)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_MAZE)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Death Spell
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See([GOODCUTOFF.0.0.0.0.SUMMONED])
  HaveSpell(WIZARD_DEATH_SPELL)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #80
    SetGlobal("MO_CastDeathSpell","LOCALS",1)
    Continue()
  RESPONSE #20
    SetGlobal("MO_CastDeathSpell","LOCALS",0)
    Continue()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastDeathSpell","LOCALS",1)
  See(Nearest([GOODCUTOFF.0.0.0.0.SUMMONED]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_DEATH_SPELL)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastDeathSpell","LOCALS",1)
  See(SecondNearest([GOODCUTOFF.0.0.0.0.SUMMONED]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_DEATH_SPELL)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastDeathSpell","LOCALS",1)
  See(ThirdNearest([GOODCUTOFF.0.0.0.0.SUMMONED]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_DEATH_SPELL)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastDeathSpell","LOCALS",1)
  See(FourthNearest([GOODCUTOFF.0.0.0.0.SUMMONED]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_DEATH_SPELL)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastDeathSpell","LOCALS",1)
  See(FifthNearest([GOODCUTOFF.0.0.0.0.SUMMONED]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_DEATH_SPELL)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastDeathSpell","LOCALS",1)
  See(SixthNearest([GOODCUTOFF.0.0.0.0.SUMMONED]))
  Allegiance(Myself,ENEMY)
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_DEATH_SPELL)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_DEATH_SPELL)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Power Word, Blind
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See([GOODCUTOFF])
  HaveSpell(WIZARD_POWER_WORD_BLIND)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastPowerWordBlind","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastPowerWordBlind","LOCALS",0)
    Continue()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastPowerWordBlind","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_BLIND)
  !HasItemEquiped("NPMISC1",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_BLIND)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastPowerWordBlind","LOCALS",1)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_BLIND)
  !HasItemEquiped("NPMISC1",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_BLIND)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastPowerWordBlind","LOCALS",1)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_BLIND)
  !HasItemEquiped("NPMISC1",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_BLIND)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastPowerWordBlind","LOCALS",1)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_BLIND)
  !HasItemEquiped("NPMISC1",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_BLIND)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastPowerWordBlind","LOCALS",1)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_BLIND)
  !HasItemEquiped("NPMISC1",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_BLIND)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastPowerWordBlind","LOCALS",1)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_BLIND)
  !HasItemEquiped("NPMISC1",LastSeenBy(Myself))
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !StateCheck(LastSeenBy(Myself),STATE_BLIND)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_BLIND)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Power Word, Stun
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See([GOODCUTOFF])
  HaveSpell(WIZARD_POWER_WORD_STUN)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastPowerWordStun","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastPowerWordStun","LOCALS",0)
    Continue()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastPowerWordStun","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_STUN)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
  !CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastPowerWordStun","LOCALS",1)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_STUN)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
  !CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastPowerWordStun","LOCALS",1)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_STUN)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
  !CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastPowerWordStun","LOCALS",1)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_STUN)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
  !CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastPowerWordStun","LOCALS",1)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_STUN)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
  !CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastPowerWordStun","LOCALS",1)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_POWER_WORD_STUN)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  !CheckSpellState(LastSeenBy(Myself),BARBARIAN_RAGE)
  !CheckSpellState(LastSeenBy(Myself),BERSERKER_RAGE)
  !CheckSpellState(LastSeenBy(Myself),MINSC_BERSERK)
  !CheckSpellState(LastSeenBy(Myself),RESIST_FEAR)
  !CheckSpellState(LastSeenBy(Myself),CHAOTIC_COMMANDS)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_DEFLECTION)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TURNING)
  !CheckStatGT(LastSeenBy(Myself),0,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_POWER_WORD_STUN)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Slow
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See([GOODCUTOFF])
  HaveSpell(WIZARD_SLOW)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastSlow","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastSlow","LOCALS",0)
    Continue()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastSlow","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_SLOW)
  !Class(LastSeenBy(Myself),MONK)
  !HasItemEquiped("ring09",LastSeenBy(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_TRANSMUTATION)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SLOW)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastSlow","LOCALS",1)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_SLOW)
  !Class(LastSeenBy(Myself),MONK)
  !HasItemEquiped("ring09",LastSeenBy(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_TRANSMUTATION)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SLOW)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastSlow","LOCALS",1)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_SLOW)
  !Class(LastSeenBy(Myself),MONK)
  !HasItemEquiped("ring09",LastSeenBy(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_TRANSMUTATION)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SLOW)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastSlow","LOCALS",1)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_SLOW)
  !Class(LastSeenBy(Myself),MONK)
  !HasItemEquiped("ring09",LastSeenBy(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_TRANSMUTATION)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SLOW)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastSlow","LOCALS",1)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_SLOW)
  !Class(LastSeenBy(Myself),MONK)
  !HasItemEquiped("ring09",LastSeenBy(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_TRANSMUTATION)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SLOW)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastSlow","LOCALS",1)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_SLOW)
  !Class(LastSeenBy(Myself),MONK)
  !HasItemEquiped("ring09",LastSeenBy(Myself))
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_TRANSMUTATION)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !CheckStatGT(LastSeenBy(Myself),0,CLERIC_FREE_ACTION)
  !CheckStatGT(LastSeenBy(Myself),25,RESISTMAGIC)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_SLOW)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Contagion
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See([GOODCUTOFF])
  HaveSpell(WIZARD_CONTAGION)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastContagion","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastContagion","LOCALS",0)
    Continue()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastContagion","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_CONTAGION)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_CONTAGION)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastContagion","LOCALS",1)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_CONTAGION)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_CONTAGION)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastContagion","LOCALS",1)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_CONTAGION)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_CONTAGION)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastContagion","LOCALS",1)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_CONTAGION)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_CONTAGION)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastContagion","LOCALS",1)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_CONTAGION)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_CONTAGION)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastContagion","LOCALS",1)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_CONTAGION)
  !Gender(LastSeenBy(Myself),SUMMONED)
  !StateCheck(LastSeenBy(Myself),STATE_SLOWED)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_CONTAGION)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Unholy Word
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See([GOODCUTOFF])
  HaveSpell(CLERIC_UNHOLY_WORD)  // SPPR715.SPL (Unholy Word)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobal("MO_CastUnholyWord","LOCALS",1)
    Continue()
  RESPONSE #50
    SetGlobal("MO_CastUnholyWord","LOCALS",0)
    Continue()
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastUnholyWord","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(CLERIC_UNHOLY_WORD)  // SPPR715.SPL (Unholy Word)
  Alignment(LastSeenBy(Myself),MASK_GOOD)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),CLERIC_UNHOLY_WORD)  // SPPR715.SPL (Unholy Word)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastUnholyWord","LOCALS",1)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(CLERIC_UNHOLY_WORD)  // SPPR715.SPL (Unholy Word)
  Alignment(LastSeenBy(Myself),MASK_GOOD)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),CLERIC_UNHOLY_WORD)  // SPPR715.SPL (Unholy Word)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastUnholyWord","LOCALS",1)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(CLERIC_UNHOLY_WORD)  // SPPR715.SPL (Unholy Word)
  Alignment(LastSeenBy(Myself),MASK_GOOD)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),CLERIC_UNHOLY_WORD)  // SPPR715.SPL (Unholy Word)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastUnholyWord","LOCALS",1)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(CLERIC_UNHOLY_WORD)  // SPPR715.SPL (Unholy Word)
  Alignment(LastSeenBy(Myself),MASK_GOOD)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),CLERIC_UNHOLY_WORD)  // SPPR715.SPL (Unholy Word)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastUnholyWord","LOCALS",1)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(CLERIC_UNHOLY_WORD)  // SPPR715.SPL (Unholy Word)
  Alignment(LastSeenBy(Myself),MASK_GOOD)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),CLERIC_UNHOLY_WORD)  // SPPR715.SPL (Unholy Word)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  Global("MO_CastUnholyWord","LOCALS",1)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(CLERIC_UNHOLY_WORD)  // SPPR715.SPL (Unholy Word)
  Alignment(LastSeenBy(Myself),MASK_GOOD)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  !CheckSpellState(LastSeenBy(Myself),SI_CONJURATION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  !CheckStatGT(LastSeenBy(Myself),0,SANCTUARY)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),CLERIC_UNHOLY_WORD)  // SPPR715.SPL (Unholy Word)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Shadow Door
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(NearestEnemyOfType([GOODCUTOFF]))
  !Allegiance(LastSeenBy(Myself),ENEMY)
  HaveSpell(WIZARD_SHADOW_DOOR)
  CheckSpellState(Myself,SI_DIVINATION)
  !StateCheck(Myself,STATE_INVISIBLE)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_SHADOW_DOOR)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Spell: Fire Shield (Blue)
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(NearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_FIRE_SHIELD_BLUE)  // SPWI403.SPL (Fire Shield (Blue))
  !CheckSpellState(Myself,RED_FIRESHIELD)
  !CheckSpellState(Myself,BLUE_FIRESHIELD)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,WIZARD_FIRE_SHIELD_BLUE)  // SPWI403.SPL (Fire Shield (Blue))
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Wondrous Recall
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  GlobalGT("MO_WondrousRecallCounter","LOCALS",1)
  See(NearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(CLERIC_WONDROUS_RECALL)  // SPPR611.SPL (Wondrous Recall)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(Myself,CLERIC_WONDROUS_RECALL)  // SPPR611.SPL (Wondrous Recall)
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: Armor of Faith
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(NearestEnemyOfType([GOODCUTOFF]))
  Range(LastSeenBy(Myself),4)
  HaveSpell(CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
  !CheckSpellState(Myself,ARMOR_OF_FAITH)
  CheckStatLT(Myself,20,SPELLFAILUREPRIEST)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #50
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    IncrementGlobal("MO_WondrousRecallCounter","LOCALS",1)
    Spell(Myself,CLERIC_ARMOR_OF_FAITH)  // SPPR111.SPL (Armor of Faith)
    SetInterrupt(TRUE)
  RESPONSE #50
    Continue()
END

/////////////////////////////////////////////////////////////////////
// Spell: WIZARD_LARLOCH_MINOR_DRAIN
/////////////////////////////////////////////////////////////////////
IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(NearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_LARLOCH_MINOR_DRAIN)
  Range(LastSeenBy(Myself),4)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_LARLOCH_MINOR_DRAIN)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(SecondNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_LARLOCH_MINOR_DRAIN)
  Range(LastSeenBy(Myself),4)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_LARLOCH_MINOR_DRAIN)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(ThirdNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_LARLOCH_MINOR_DRAIN)
  Range(LastSeenBy(Myself),4)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_LARLOCH_MINOR_DRAIN)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(FourthNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_LARLOCH_MINOR_DRAIN)
  Range(LastSeenBy(Myself),4)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_LARLOCH_MINOR_DRAIN)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(FifthNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_LARLOCH_MINOR_DRAIN)
  Range(LastSeenBy(Myself),4)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_LARLOCH_MINOR_DRAIN)
    SetInterrupt(TRUE)
END

IF
  OR(2)
    !GlobalTimerNotExpired("MO_SpellCastTimer","LOCALS")
    CheckStatGT(Myself,0,AURACLEANSING)
  See(SixthNearestEnemyOfType([GOODCUTOFF]))
  HaveSpell(WIZARD_LARLOCH_MINOR_DRAIN)
  Range(LastSeenBy(Myself),4)
  !Gender(LastSeenBy(Myself),SUMMONED)
  CheckStatLT(LastSeenBy(Myself),50,RESISTMAGIC)
  !CheckSpellState(LastSeenBy(Myself),SI_NECROMANCY)
  !StateCheck(LastSeenBy(Myself),STATE_NOT_TARGETABLE)
  !StateCheck(LastSeenBy(Myself),STATE_IMPROVEDINVISIBILITY)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_DEFLECTION)
  CheckStatLT(LastSeenBy(Myself),1,WIZARD_SPELL_TURNING)
  !CheckStat(LastSeenBy(Myself),1,WIZARD_SPELL_TRAP)
  !CheckStat(LastSeenBy(Myself),1,CLERIC_SHIELD_OF_THE_ARCHONS)
  CheckStat(LastSeenBy(Myself),0,MINORGLOBE)
  !StateCheck(LastSeenBy(Myself),STATE_HARMLESS)
  CheckStatLT(Myself,20,SPELLFAILUREMAGE)
  !CheckStatGT(Myself,0,CLERIC_INSECT_PLAGUE)
  !StateCheck(Myself,STATE_POISONED)
  !StateCheck(Myself,STATE_SILENCED)
THEN
  RESPONSE #100
    SetGlobalTimer("MO_SpellCastTimer","LOCALS",6)
    SetInterrupt(FALSE)
    Spell(LastSeenBy(Myself),WIZARD_LARLOCH_MINOR_DRAIN)
    SetInterrupt(TRUE)
END

/////////////////////////////////////////////////////////////////////
// Find them! (Experimental)
/////////////////////////////////////////////////////////////////////
IF
  Heard([ENEMY],125)
  !Detect([GOODCUTOFF])
  Allegiance(Myself,ENEMY)
THEN
  RESPONSE #100
    MoveToObject(LastHeardBy(Myself))
END
