IF
	IsOverMe([GOODCUTOFF])
	Global("MO_Spawn07","MOBHA1",0)
THEN
	RESPONSE #100
		SetGlobal("MO_Spawn07","MOBHA1",1)
		CreateCreature("mobha43",[1805.666],NW)  // Phiuhl
		CreateCreature("mobha43",[1851.655],NW)  // Phiuhl
		CreateCreature("mobha43",[1816.701],NW)  // Phiuhl
		//CreateCreature("mobha05",[1934.651],W)   // Scout
		//CreateCreature("mobha05",[1851.800],NW)  // Scout
		//CreateCreature("mobha07",[1908.734],W)   // Shadowdancer
END

