/////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////////////////
//            Mutant Fomorian Giant
/////////////////////////////////////////////////////////////////////
//        Version 1
// Mutant Fomorian Giant, 25th level Fighter
//
//
/////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////
// Initial Set-Up
/////////////////////////////////////////////////////////////////////
IF
  See([GOODCUTOFF])
  Global("Prep","LOCALS",0)
  Allegiance(Myself,ENEMY)
  DifficultyGT(HARD)
THEN
  RESPONSE #100
    SetGlobal("Prep","LOCALS",1)
    ApplySpell(Myself,WARRIOR_GREATER_WHIRLWIND)
    ReallyForceSpell(Myself,CLERIC_INSECT_PLAGUE)
    ReallyForceSpell(Myself,WIZARD_EMOTION_HOPELESSNESS)
    SetGlobal("MO_GWW","LOCALS",2)
    Continue()
END

IF
  See([GOODCUTOFF])
  Global("Prep","LOCALS",0)
  Allegiance(Myself,ENEMY)
  DifficultyLT(HARDEST)
THEN
  RESPONSE #100
    SetGlobal("Prep","LOCALS",1)
    ReallyForceSpell(Myself,WIZARD_EMOTION_HOPELESSNESS)
    ReallyForceSpell(Myself,WIZARD_IMPROVED_HASTE)
    SetGlobal("MO_GWW","LOCALS",0)
    Continue()
END