IF
	IsOverMe([GOODCUTOFF])
	Global("MO_Spawn05","MOBHA1",0)
THEN
	RESPONSE #100
		SetGlobal("MO_Spawn05","MOBHA1",1)
		CreateCreature("mobha06",[1943.161],E)  // Skirmisher
		CreateCreature("mobha06",[1954.244],E)  // Skirmisher
		CreateCreature("mobha05",[1878.157],E)  // Scout
		CreateCreature("mobha05",[1891.240],E)  // Scout
		CreateCreature("mobha07",[2061.172],E)  // Shadowdancer
		CreateCreature("mobha08",[2063.255],E)  // Assassin
END