IF
    True()
THEN
    RESPONSE #100
        CutSceneId("MOBHA28a")
        MoveViewObject(Myself,INSTANT)
        Explore()
        Wait(1)
        CreateVisualEffect("CALLLIGH",[917.483])
        PlaySound("EFF_P19")
        Wait(2)
        ScreenShake([5.5],30)
        CreateVisualEffect("spcallli",[917.483])
        PlaySound("EFF_P35a")
        Wait(2)
        CreateCreature("MOBHA44",[917.483],W)  // Uthaedeol the Blood-drenched
        Wait(1)
        EndCutSceneMode()
END
