IF
	True()
THEN
	RESPONSE #100
		CutSceneId(Player1)
		CreateCreatureDoor("mobha13",[1233.450],E)  // Fallen Planetar
		CreateCreatureDoor("mobha14",[1464.242],E)  // Fallen Deva
		CreateCreatureDoor("mobha14",[1582.282],E)  // Fallen Deva
		CreateCreatureDoor("mobha12",[1265.443],E)  // Fallen Planetar
		CreateCreatureDoor("mobha12",[1392.485],E)  // Fallen Planetar
		Wait(4)
		EndCutSceneMode()
END