// The Crucible

///////////////////////////////////////////////////////////////////////////
// Import                                                                //
///////////////////////////////////////////////////////////////////////////

//-------------------------------------------------------------------------
// General Import
COPY ~crucible/are~ ~override~
COPY ~crucible/bam~ ~override~
COPY ~crucible/wav~ ~override~

//-------------------------------------------------------------------------
// Convert OGG to WAV (Thanks Cam!)
LAF HANDLE_AUDIO END

//-------------------------------------------------------------------------
// 2da Import
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~fogarea.2da~) THEN BEGIN
  COPY ~%MOD_FOLDER%/2da/fogarea.2da~ ~override~
END

ACTION_IF NOT (FILE_EXISTS_IN_GAME ~fogpt.2da~) THEN BEGIN
  COPY ~%MOD_FOLDER%/2da/fogpt.2da~ ~override~
END

APPEND ~MASTAREA.2da~ ~MOBHA1 value~
APPEND ~FOGAREA.2da~ ~MOBHA1  0.80  75  58  62   95   44  53   75   25~
UNLESS ~MOBHA1~

//-------------------------------------------------------------------------
// Deathbringer (Halberd)
COPY ~crucible/cre/mobha01.cre~ ~override/mobha01.cre~
  SAY NAME1 @2000
  SAY NAME2 @2000

//-------------------------------------------------------------------------
// Deathbringer (2h Sword)
COPY ~crucible/cre/mobha02.cre~ ~override/mobha02.cre~
  SAY NAME1 @2000
  SAY NAME2 @2000

//-------------------------------------------------------------------------
// Entropic Reaper - Animations provided by Acifer, THANK YOU!
LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
ACTION_IF (slot <= 0) BEGIN
  FAIL ~No free creature animation slot found.~
END

LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
APPEND ~animate.ids~ ~0x%hexNumber% AC#MERRENOLOTH~ UNLESS ~AC#MERRENOLOTH~
CLEAR_IDS_MAP

COPY ~crucible/animations/merrenoloth/exxx.ini~ ~override/%hexNumber%.ini~

ACTION_BASH_FOR ~crucible/animations/merrenoloth~ ~^.+\.bam$~ BEGIN
  COPY ~%BASH_FOR_FILESPEC%~ ~override~
END

COPY ~crucible/cre/mobha03.cre~ ~override~  // Entropic Reaper
  SAY NAME1 @2001
  SAY NAME2 @2001
  WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~AC#MERRENOLOTH~))

COPY ~crucible/spl/mobha03.spl~ ~override~  // Entropic Reaper Crit bonus (x4)
COPY ~crucible/itm/mobha03.itm~ ~override~  // Entropic Reaper Scythe

//-------------------------------------------------------------------------
// Bebilith - Animations provided by Acifer, THANK YOU!
LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
ACTION_IF (slot <= 0) BEGIN
  FAIL ~No free creature animation slot found.~
END

LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
APPEND ~animate.ids~ ~0x%hexNumber% AC#BEBILITH~ UNLESS ~AC#BEBILITH~
CLEAR_IDS_MAP

COPY ~crucible/animations/bebilith/exxx.ini~ ~override/%hexNumber%.ini~

ACTION_BASH_FOR ~crucible/animations/bebilith~ ~^.+\.bam$~ BEGIN
  COPY ~%BASH_FOR_FILESPEC%~ ~override~
END

COPY ~crucible/cre/mobha04.cre~ ~override~  // Bebilith
  SAY NAME1 @2002
  SAY NAME2 @2002
  WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~AC#BEBILITH~))

COPY ~crucible/spl/mobha04.spl~  ~override~  // Flaming Web
  SAY NAME1 @4000
  SAY NAME2 @4000
COPY ~crucible/itm/mobha04a.itm~ ~override~  // Claw
COPY ~crucible/itm/mobha04b.itm~ ~override~  // Bite

//-------------------------------------------------------------------------
// Scout (Ranged)
COPY ~crucible/cre/mobha05.cre~ ~override/mobha05.cre~
  SAY NAME1 @2003
  SAY NAME2 @2003

//-------------------------------------------------------------------------
// Skirmisher (Melee)
COPY ~crucible/cre/mobha06.cre~ ~override/mobha06.cre~
  SAY NAME1 @2004
  SAY NAME2 @2004

//-------------------------------------------------------------------------
// Shadowdancer
COPY ~crucible/cre/mobha07.cre~ ~override/mobha07.cre~
  SAY NAME1 @2005
  SAY NAME2 @2005

//-------------------------------------------------------------------------
// Assassin
COPY ~crucible/cre/mobha08.cre~ ~override/mobha08.cre~
  SAY NAME1 @2006
  SAY NAME2 @2006

//-------------------------------------------------------------------------
// Balor
COPY ~crucible/cre/mobha09.cre~  ~override/mobha09.cre~
COPY ~crucible/itm/mobha09a.itm~ ~override~  // Claw
COPY ~crucible/itm/mobha09b.itm~ ~override~  // Bite

//-------------------------------------------------------------------------
// Balor w/ heart
COPY ~crucible/itm/mobha10a.itm~ ~override~  // Demon Heart
COPY ~crucible/cre/mobha09.cre~  ~override/mobha10.cre~
  SAY NAME1 @2008
  SAY NAME2 @2008
  WRITE_ASCII 0x248 ~shoutdlg~ #8 // Override Script
  WRITE_ASCII 0x280 ~mobha10~  #8 // Script Name
  WRITE_ASCII 0x2cc ~mobha10~  #8 // Dialogue
  REPLACE_CRE_ITEM ~mobha10a~  #0 #0 #0 ~UNSTEALABLE~ ~INV1~ EQUIP // Demon Heart
COMPILE EVALUATE_BUFFER ~crucible/dlg/mobha10.d~

//-------------------------------------------------------------------------
// Glabrezu
COPY ~crucible/cre/mobha11.cre~  ~override/mobha11.cre~

//-------------------------------------------------------------------------
// Fallen Planetar
COPY ~crucible/cre/mobha12.cre~  ~override/mobha12.cre~

//-------------------------------------------------------------------------
// Fallen Planetar w/ Feather
COPY ~crucible/itm/mobha13a.itm~ ~override~  // Angel Feather
COPY ~crucible/cre/mobha12.cre~  ~override/mobha13.cre~
  SAY NAME1 @2009
  SAY NAME2 @2009
  WRITE_ASCII 0x248 ~shoutdlg~ #8 // Override Script
  WRITE_ASCII 0x280 ~mobha13~  #8 // Script Name
  WRITE_ASCII 0x2cc ~mobha13~  #8 // Dialogue
  REPLACE_CRE_ITEM ~mobha13a~  #0 #0 #0 ~UNSTEALABLE~ ~INV1~ EQUIP // Angel Feather
COMPILE EVALUATE_BUFFER ~crucible/dlg/mobha13.d~

//-------------------------------------------------------------------------
// Fallen Deva
COPY ~crucible/cre/mobha14.cre~  ~override/mobha14.cre~

//-------------------------------------------------------------------------
// Demon Knight
COPY ~crucible/cre/mobha15.cre~  ~override/mobha15.cre~

//-------------------------------------------------------------------------
// Erinyes
COPY ~crucible/cre/mobha16.cre~  ~override/mobha16.cre~
COPY ~crucible/itm/mobha16a.itm~ ~override~  // Long Sword
COPY ~crucible/itm/mobha16b.itm~ ~override~  // Arrows

//-------------------------------------------------------------------------
// Deathstalker
COPY ~crucible/cre/mobha17.cre~  ~override/mobha17.cre~
  SAY NAME1 @2010
  SAY NAME2 @2010
  WRITE_ASCII 0x2cc ~MOBHA17~ #8 // Dialogue
COMPILE EVALUATE_BUFFER ~crucible/dlg/mobha17.d~

//-------------------------------------------------------------------------
// Deathstalker (Initial Discussion)
COPY ~crucible/cre/mobha17.cre~  ~override/mobha18.cre~
  SAY NAME1 @2007
  SAY NAME2 @2007
  WRITE_ASCII 0x268 ~~        #8 // Clear Default Script
  WRITE_ASCII 0x280 ~MOBHA18~ #8 // Script Name
  WRITE_ASCII 0x2cc ~MOBHA18~ #8 // Dialogue
  REPLACE_CRE_ITEM ~MIN1HP~ #0 #0 #0 ~UNSTEALABLE&UNDROPPABLE~ ~LRING~ EQUIP // Make invincible
COMPILE EVALUATE_BUFFER ~crucible/dlg/mobha18.d~

//-------------------------------------------------------------------------
// Statue
COPY ~crucible/cre/mobha19.cre~  ~override/mobha19.cre~
  WRITE_ASCII 0x2cc ~MOBHA19~ #8 // Dialogue
COMPILE EVALUATE_BUFFER ~crucible/dlg/mobha19.d~

//-------------------------------------------------------------------------
// Marilith (Sapphira)
COPY ~crucible/cre/mobha20.cre~  ~override/mobha20.cre~
  SAY NAME1 @2011
  SAY NAME2 @2011
  WRITE_ASCII 0x2cc ~MOBHA20~ #8 // Dialogue
COMPILE EVALUATE_BUFFER ~crucible/dlg/mobha20.d~

//-------------------------------------------------------------------------
// Succubus
COPY ~crucible/cre/mobha21.cre~  ~override/mobha21.cre~
COPY ~crucible/itm/mobha21a.itm~ ~override~  // Weapon

//-------------------------------------------------------------------------
// Kirinhale (Succubus)
COPY ~crucible/cre/mobha21.cre~  ~override/mobha22.cre~
  SAY NAME1 @2012
  SAY NAME2 @2012

///////////////////////////////////////////////////////////////////////////
// Dialog                                                                //
///////////////////////////////////////////////////////////////////////////
ACTION_IF ascension BEGIN
  COMPILE ~crucible/dlg/update_transition2.d~
END ELSE BEGIN
  COMPILE ~crucible/dlg/update_transition1.d~
END

///////////////////////////////////////////////////////////////////////////
// Copy .BCS file to override folder                                     //
///////////////////////////////////////////////////////////////////////////
ACTION_IF ascension BEGIN
  COPY ~crucible/baf/motob02.baf~ ~override/motob01.bcs~
    COMPILE_BAF_TO_BCS
END ELSE BEGIN
  COPY ~crucible/baf/motob01.baf~ ~override/motob01.bcs~
    COMPILE_BAF_TO_BCS
END

COPY ~crucible/baf/mobha1.baf~  ~override/mobha1.bcs~   // Area script
     ~crucible/baf/mobha1a.baf~ ~override/mobha1a.bcs~  // Area script
     ~crucible/baf/mobha1b.baf~ ~override/mobha1b.bcs~  // Area script
     ~crucible/baf/mobha1c.baf~ ~override/mobha1c.bcs~  // Area script
     ~crucible/baf/mobha1d.baf~ ~override/mobha1d.bcs~  // Area script
     ~crucible/baf/mobha1e.baf~ ~override/mobha1e.bcs~  // Area script
     ~crucible/baf/mobha1f.baf~ ~override/mobha1f.bcs~  // Area script
     ~crucible/baf/mobha1g.baf~ ~override/mobha1g.bcs~  // Area script
     ~crucible/baf/mobha1h.baf~ ~override/mobha1h.bcs~  // Area script
     ~crucible/baf/mobha1i.baf~ ~override/mobha1i.bcs~  // Area script
     ~crucible/baf/mobha1j.baf~ ~override/mobha1j.bcs~  // Area script
     ~crucible/baf/mobha1k.baf~ ~override/mobha1k.bcs~  // Area script
     ~crucible/baf/mobha1l.baf~ ~override/mobha1l.bcs~  // Area script
     ~crucible/baf/mobha3.baf~  ~override/mobha3.bcs~   // Area script
     ~crucible/baf/mobha6.baf~  ~override/mobha6.bcs~   // Area script
     ~crucible/baf/mobha6a.baf~ ~override/mobha6a.bcs~  // Area script
     ~crucible/baf/mobha6b.baf~ ~override/mobha6b.bcs~  // Area script
     ~crucible/baf/mobha6c.baf~ ~override/mobha6c.bcs~  // Area script
     ~crucible/baf/mobha01.baf~ ~override/mobha01.bcs~  // Creature script
     ~crucible/baf/mobha03.baf~ ~override/mobha03.bcs~  // Creature script
     ~crucible/baf/mobha04.baf~ ~override/mobha04.bcs~  // Creature script
     ~crucible/baf/mobha05.baf~ ~override/mobha05.bcs~  // Creature script
     ~crucible/baf/mobha06.baf~ ~override/mobha06.bcs~  // Creature script
     ~crucible/baf/mobha07.baf~ ~override/mobha07.bcs~  // Creature script
     ~crucible/baf/mobha08.baf~ ~override/mobha08.bcs~  // Creature script
     ~crucible/baf/mobha09.baf~ ~override/mobha09.bcs~  // Creature script
     ~crucible/baf/mobha11.baf~ ~override/mobha11.bcs~  // Creature script
     ~crucible/baf/mobha12.baf~ ~override/mobha12.bcs~  // Creature script
     ~crucible/baf/mobha14.baf~ ~override/mobha14.bcs~  // Creature script
     ~crucible/baf/mobha15.baf~ ~override/mobha15.bcs~  // Creature script
     ~crucible/baf/mobha16.baf~ ~override/mobha16.bcs~  // Creature script
     ~crucible/baf/mobha17.baf~ ~override/mobha17.bcs~  // Creature script
     ~crucible/baf/mobha20.baf~ ~override/mobha20.bcs~  // Creature script
     ~crucible/baf/mobha21.baf~ ~override/mobha21.bcs~  // Creature script
     //~crucible/baf/mocut03.baf~ ~override/mocut03.bcs~  // Cutscene script
  COMPILE_BAF_TO_BCS