// The Crucible

///////////////////////////////////////////////////////////////////////////
// Import                                                                //
///////////////////////////////////////////////////////////////////////////

//-------------------------------------------------------------------------
// General Import
COPY ~crucible/are~ ~override~
COPY ~crucible/bam~ ~override~
COPY ~crucible/wav~ ~override~

//-------------------------------------------------------------------------
// 2da Import
ACTION_IF NOT (FILE_EXISTS_IN_GAME ~fogarea.2da~) THEN BEGIN
  COPY ~%MOD_FOLDER%/2da/fogarea.2da~ ~override~
END

ACTION_IF NOT (FILE_EXISTS_IN_GAME ~fogpt.2da~) THEN BEGIN
  COPY ~%MOD_FOLDER%/2da/fogpt.2da~ ~override~
END

APPEND ~MASTAREA.2da~ ~MOBHA1 value~
APPEND ~FOGAREA.2da~ ~MOBHA1  0.80  75  58  62   95   44  53   75   25~
UNLESS ~MOBHA1~

//-------------------------------------------------------------------------
// Deathbringer (Halberd)
COPY ~crucible/cre/mobha01.cre~ ~override/mobha01.cre~
  SAY NAME1 @2000
  SAY NAME2 @2000

//-------------------------------------------------------------------------
// Deathbringer (2h Sword)
COPY ~crucible/cre/mobha02.cre~ ~override/mobha02.cre~
  SAY NAME1 @2000
  SAY NAME2 @2000

//-------------------------------------------------------------------------
// Entropic Reaper - Animations provided by Acifer, THANK YOU!
LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
ACTION_IF (slot <= 0) BEGIN
  FAIL ~No free creature animation slot found.~
END

LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
APPEND ~animate.ids~ ~0x%hexNumber% AC#MERRENOLOTH~ UNLESS ~AC#MERRENOLOTH~
CLEAR_IDS_MAP

COPY ~crucible/animations/merrenoloth/exxx.ini~ ~override/%hexNumber%.ini~

ACTION_BASH_FOR ~crucible/animations/merrenoloth~ ~^.+\.bam$~ BEGIN
  COPY ~%BASH_FOR_FILESPEC%~ ~override~
END

COPY ~crucible/cre/mobha03.cre~ ~override~  // Entropic Reaper
  SAY NAME1 @2001
  SAY NAME2 @2001
  WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~AC#MERRENOLOTH~))

COPY ~crucible/spl/mobha03.spl~ ~override~  // Entropic Reaper Crit bonus (x4)
COPY ~crucible/itm/mobha03.itm~ ~override~  // Entropic Reaper Scythe

//-------------------------------------------------------------------------
// Bebilith - Animations provided by Acifer, THANK YOU!
LAF FIND_FREE_ANIM_SLOT INT_VAR slotMin = 0xE000 slotMax = 0xefff RET slot END
ACTION_IF (slot <= 0) BEGIN
  FAIL ~No free creature animation slot found.~
END

LAF TO_HEX_NUMBER INT_VAR value = slot minDigits = 4 RET hexNumber END
APPEND ~animate.ids~ ~0x%hexNumber% AC#BEBILITH~ UNLESS ~AC#BEBILITH~
CLEAR_IDS_MAP

COPY ~crucible/animations/bebilith/exxx.ini~ ~override/%hexNumber%.ini~

ACTION_BASH_FOR ~crucible/animations/bebilith~ ~^.+\.bam$~ BEGIN
  COPY ~%BASH_FOR_FILESPEC%~ ~override~
END

COPY ~crucible/cre/mobha04.cre~ ~override~  // Bebilith
  SAY NAME1 @2002
  SAY NAME2 @2002
  WRITE_LONG 0x28 (IDS_OF_SYMBOL (~animate~ ~AC#BEBILITH~))

COPY ~crucible/spl/mobha04.spl~  ~override~  // Flaming Web
  SAY NAME1 @4000
  SAY NAME2 @4000
COPY ~crucible/itm/mobha04a.itm~ ~override~  // Claw
COPY ~crucible/itm/mobha04b.itm~ ~override~  // Bite

//-------------------------------------------------------------------------
// Scout (Ranged)
COPY ~crucible/cre/mobha05.cre~ ~override/mobha05.cre~
  SAY NAME1 @2003
  SAY NAME2 @2003

//-------------------------------------------------------------------------
// Skirmisher (Melee)
COPY ~crucible/cre/mobha06.cre~ ~override/mobha06.cre~
  SAY NAME1 @2004
  SAY NAME2 @2004

//-------------------------------------------------------------------------
// Shadowdancer
COPY ~crucible/cre/mobha07.cre~ ~override/mobha07.cre~
  SAY NAME1 @2005
  SAY NAME2 @2005

//-------------------------------------------------------------------------
// Assassin
COPY ~crucible/cre/mobha08.cre~ ~override/mobha08.cre~
  SAY NAME1 @2006
  SAY NAME2 @2006

///////////////////////////////////////////////////////////////////////////
// Dialog                                                                //
///////////////////////////////////////////////////////////////////////////
ACTION_IF ascension BEGIN
  COMPILE ~crucible/dlg/update_transition2.d~
END ELSE BEGIN
  COMPILE ~crucible/dlg/update_transition1.d~
END

///////////////////////////////////////////////////////////////////////////
// Copy .BCS file to override folder                                     //
///////////////////////////////////////////////////////////////////////////
ACTION_IF ascension BEGIN
  COPY ~crucible/baf/motob02.baf~ ~override/motob01.bcs~
    COMPILE_BAF_TO_BCS
END ELSE BEGIN
  COPY ~crucible/baf/motob01.baf~ ~override/motob01.bcs~
    COMPILE_BAF_TO_BCS
END

COPY ~crucible/baf/mobha1.baf~  ~override/mobha1.bcs~   // Area script
     ~crucible/baf/mobha1a.baf~ ~override/mobha1a.bcs~  // Area script
     ~crucible/baf/mobha1b.baf~ ~override/mobha1b.bcs~  // Area script
     ~crucible/baf/mobha3.baf~  ~override/mobha3.bcs~   // Area script
     ~crucible/baf/mobha01.baf~ ~override/mobha01.bcs~  // Creature script
     ~crucible/baf/mobha03.baf~ ~override/mobha03.bcs~  // Creature script
     ~crucible/baf/mobha04.baf~ ~override/mobha04.bcs~  // Creature script
     ~crucible/baf/mobha05.baf~ ~override/mobha05.bcs~  // Creature script
     ~crucible/baf/mobha06.baf~ ~override/mobha06.bcs~  // Creature script
     ~crucible/baf/mobha07.baf~ ~override/mobha07.bcs~  // Creature script
     ~crucible/baf/mobha08.baf~ ~override/mobha08.bcs~  // Creature script
  COMPILE_BAF_TO_BCS