COPY ~crucible/baf/mobha37.baf~ ~crucible/baf/mobha37.baf~

///////////////////////////////////////////////////////////////////////////
// Update Prebuffs                                                       //
///////////////////////////////////////////////////////////////////////////
  LPF REPLACE_MULTILINE
    INT_VAR
    strict = 1
    verbose = 0
    STR_VAR
    pattern = ~~~~~// IWD Prebuffs~~~~~
    string = ~~~~~ApplySpell(Myself,CLERIC_GREATER_SHIELD_OF_LATHANDER)
    ApplySpell(Myself,CLERIC_RECITATION)
    ApplySpell(Myself,CLERIC_PRAYER)
    ApplySpell(Myself,CLERIC_ENTROPY_SHIELD)
    ApplySpell(Myself,CLERIC_IMPERVIOUS_SANCTITY_OF_MIND)~~~~~ //"
  END
